  localstack:
    image: localstack/localstack
    expose:
      - '4569'
    ports:
      - '4569:4569'
    environment:
      SERVICES: 'dynamodb'
      HOSTNAME: 'localstack'
      HOSTNAME_EXTERNAL: 'localstack'

  dynamo_admin:
    image: aaronshaf/dynamodb-admin
    expose:
      - '8001'
    environment:
      - DYNAMO_ENDPOINT=http://localstack:4569
    links:
      - localstack
    ports:
      - '8000:8001'