  version: '3.2'
  services:
    localstack:
      image: localstack/localstack
      expose:
        - '4569'
      ports:
        - '4569:4569'
      environment:
        SERVICES: 'dynamodb'
        HOSTNAME: 'localstack'
        HOSTNAME_EXTERNAL: 'localstack'

    dynamo_admin:
      image: aaronshaf/dynamodb-admin
      expose:
        - '8001'
      environment:
        - DYNAMO_ENDPOINT=http://localstack:4569
      links:
        - localstack
      ports:
        - '8000:8001'

    import_data:
      build: data
      links:
        - dynamo_admin
      command: python import-to-dynamo.py 
      volumes:
        - type: bind
          source: ./data
          target: /data
      environment: 
        AWS_DEFAULT_REGION: 'eu-west-1'
        AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
        AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
        AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}